### ISSUE TITLE
Missing privacy manifest

### ISSUE THREAD

**Issue by cicerocamargo** [GeeTeam/gt3-spm-repo#2]
Hello everyone! 
This is Cicero speaking in behalf of [Airtm](https://airtm.com)'s Tech team.

As we prepare for the upcoming enforcement of Apple's requirement for a privacy manifest in iOS apps and SDKs **starting from May 1st**, we've been reviewing our integrations, particularly with regards to our most sensitive SDKs. Among these, `GT3Captcha` stands out, as it collects device info but currently does not include a privacy manifest.

We understand the importance of compliance with these guidelines and wanted to inquire whether you are currently working on updating your SDK to include the required privacy manifest. Alternatively, if there is a version of the framework with this information that is not publicly available yet, we would greatly appreciate any insight or assistance you can provide on this matter.

Thanks in advance.
Best regards,
Cícero

**Comment by cicerocamargo** [comment]
I saw that you do have the Privacy manifest in the cocoapods repo (https://github.com/GeeTeam/gt3-ios-cocoapods-support/blob/master/SDK/GT3Captcha.framework/PrivacyInfo.xcprivacy) so I believe it's just a matter of updating this one.

**Comment by sunnyGeetest** [comment]
@cicerocamargo 

We have updated the SDK, please update to the latest version.

**Comment by cicerocamargo** [comment]
Hey @sunnyGeetest! Thanks for the update.
I just downloaded the new version here and it worked fine!
However, I had to point to the `main` branch, as SPM won't find version `0.15.8.4` nor `0.15.8`.
The major problem here is that if you push a new version to the `main` branch and we take this update without noticing it, we'll have the wrong `GT3Captcha.bundle` added to our project...

Can you take a look at version issue?

Also, it would be really nice if you can access the bundle shipped with the framework, instead of having to reach out to the host app to get the bundle ref.

Thanks in advance.

**Comment by sunnyGeetest** [comment]
@cicerocamargo 
Thank you for your feedback. The resource file based on `GT3Captcha.bundle` is relatively fixed. In most cases, we will not modify this file every time we release a new version. 

We are also looking for an operation that does not require you to manually integrate `GT3Captcha.bundle`. If there is a good solution, we will update it immediately.
